# Generated by Django 3.2.7 on 2021-09-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
